#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
# Gradle wrapper script for POSIX generated by Gradle.
#
# Compatible with Bash 3.2+

# Attempt to set APP_HOME
# Resolve links: $0 may be an a file, directory or program
PRG="$0"
# Need this for relative symlinks called from root directory
while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=${ls#*' -> '}
    case $link in             #(
      /*)                 PRG="${link}/$PRG" ;;
      /*)                 PRG="${link}${PRG:#[^/]*}" ;;
      *)                 PRG="${link}" ;;
    esac
done
SAVED="`pwd`"
cd "`dirname "$PRG"`" >/dev/null 2>&1
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null 2>&1

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can
MAX_FD=maximum
case $MAX_FD in
    maximum|max)
        MAX_FD=maximum
        ;;
esac

# Escape application args
save () {
    for i do printf %s\\n "$i" ; done
}

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $(eval echo $(printf '%s\n' "$GRADLE_OPTS" | sed -e "s/'/'\\\\''/g") | tr '\n' ' ')
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $(eval echo $(printf '%s\n' "$GRADLE_OPTS" | sed -e "s/'/'\\\\''/g") | tr '\n' ' ')

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $(eval echo $(printf '%s\n' "$GRADLE_OPTS" | sed -e "s/'/'\\\\''/g") | tr '\n' ' ')

# For Cygwin, switch paths to Windows format before running java
if $cygwin ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $(eval echo $(printf '%s\n' "$GRADLE_OPTS" | sed -e "s/'/'\\\\''/g") | tr '\n' ' ')

exec "$JAVACMD" "$@"
